# Numpy

In [1]:
mylist = [1,4,7,8]
mylist

[1, 4, 7, 8]

In [2]:
mylist = mylist*2

In [3]:
mylist

[1, 4, 7, 8, 1, 4, 7, 8]

In [4]:
mylist2 = []
for val in mylist:
    mylist2.append(val*2)
    
print(mylist2)

[2, 8, 14, 16, 2, 8, 14, 16]


In [5]:
l1 = [[1,5,9,6],[5,6,4,8],[7,8,2,3]]

In [6]:
l1

[[1, 5, 9, 6], [5, 6, 4, 8], [7, 8, 2, 3]]

**Numpy Array**

In [7]:
import numpy as np

In [8]:
a = np.array([1,7,9,3])

In [9]:
print(a)

[1 7 9 3]


In [10]:
print(a*2)

[ 2 14 18  6]


In [11]:
b = np.array([[1,5,9,6],[5,6,4,8],[7,8,2,3]])

In [12]:
print(b)

[[1 5 9 6]
 [5 6 4 8]
 [7 8 2 3]]


In [13]:
print(b*2)

[[ 2 10 18 12]
 [10 12  8 16]
 [14 16  4  6]]


In [14]:
print(b.shape)
print(b.size)
print(b.ndim)

(3, 4)
12
2


In [15]:
print(b[0])

[1 5 9 6]


In [16]:
print(b[1])

[5 6 4 8]


In [17]:
print(b[2])

[7 8 2 3]


In [18]:
#address of any value - array[row index,column index]
print(b[0,1])
print(b[0][1])
print(b[1,3])

5
5
8


In [19]:
c = np.array([[1,5,9,6],[5,'ABC',4,8],[7,8,2,3]])
print(c)

[['1' '5' '9' '6']
 ['5' 'ABC' '4' '8']
 ['7' '8' '2' '3']]


In [20]:
d = np.array([[5, 8, 8, 9, 4, 2], [5, 9, 6, 3, 2, 1], [5, 9, 8, 6, 5, 4]])
print(d)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [21]:
#array[initial row index : initial row index+steps , initial col index:intial col index+steps]
print(d[0:3 , 0:6])

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [22]:
#array[initial row index : initial row index+steps , initial col index:intial col index+steps]
print(d[1:3 , 2:5])

[[6 3 2]
 [8 6 5]]


In [23]:
#copy the array in different array
bs = d[1:3 , 2:5].copy()
bs

array([[6, 3, 2],
       [8, 6, 5]])

In [24]:
bs.shape

(2, 3)

In [25]:
#replace the content of array[index]
bs[0,1] = 33
print(bs)

[[ 6 33  2]
 [ 8  6  5]]


In [26]:
d

array([[5, 8, 8, 9, 4, 2],
       [5, 9, 6, 3, 2, 1],
       [5, 9, 8, 6, 5, 4]])

In [27]:
e = np.array([[[5,7,6,4] , [7,5,4,2] , [6,8,9,3]] , [[5,9,8,7] , [3,7,3,2] , [5,9,8,5]]])

In [28]:
e

array([[[5, 7, 6, 4],
        [7, 5, 4, 2],
        [6, 8, 9, 3]],

       [[5, 9, 8, 7],
        [3, 7, 3, 2],
        [5, 9, 8, 5]]])

In [29]:
print(e.shape)
print(e.size)
print(e.ndim)

(2, 3, 4)
24
3


In [30]:
#array[floor index,row index,column index]
print(e[0,2,2])
print(e[1,2,2])

9
8


In [31]:
b = np.array([[5, 8, 8, 9, 4, 2], [5, 9, 6, 3, 2, 1], [5, 9, 8, 6, 5, 4]])
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [32]:
print(np.sum(b))
print(np.prod(b))
print(np.min(b))
print(np.max(b))
print(np.mean(b))
print(np.std(b))
print(np.argmax(b))
print(np.argmin(b))

99
1818624000
1
9
5.5
2.5
3
11


In [33]:
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [34]:
#for column analysis
print(np.sum(b , axis=0))
print(np.prod(b , axis=0))
print(np.min(b , axis=0))
print(np.max(b , axis=0))
print(np.mean(b , axis=0))
print(np.std(b , axis=0))
print(np.argmax(b , axis=0))
print(np.argmin(b , axis=0))

[15 26 22 18 11  7]
[125 648 384 162  40   8]
[5 8 6 3 2 1]
[5 9 8 9 5 4]
[5.         8.66666667 7.33333333 6.         3.66666667 2.33333333]
[0.         0.47140452 0.94280904 2.44948974 1.24721913 1.24721913]
[0 1 0 0 2 2]
[0 0 1 1 1 1]


In [35]:
print(b)

[[5 8 8 9 4 2]
 [5 9 6 3 2 1]
 [5 9 8 6 5 4]]


In [36]:
#for row analysis
print(np.sum(b , axis=1))
print(np.prod(b , axis=1))
print(np.min(b , axis=1))
print(np.max(b , axis=1))
print(np.mean(b , axis=1))
print(np.std(b , axis=1))
print(np.argmax(b , axis=1))
print(np.argmin(b , axis=1))

[36 26 37]
[23040  1620 43200]
[2 1 4]
[9 9 9]
[6.         4.33333333 6.16666667]
[2.51661148 2.68741925 1.77169097]
[3 1 1]
[5 5 5]


In [37]:
b = np.array([[5, 8, 8, -9, 4, 2], [5, 9, 6, 3, 2, 1], [5, 9, 8, 6, 5, 4]])
print(b)

[[ 5  8  8 -9  4  2]
 [ 5  9  6  3  2  1]
 [ 5  9  8  6  5  4]]


In [38]:
#Sort of row element
np.sort(b,axis=1)

array([[-9,  2,  4,  5,  8,  8],
       [ 1,  2,  3,  5,  6,  9],
       [ 4,  5,  5,  6,  8,  9]])

In [39]:
#Sort of column element
np.sort(b,axis=0)

array([[ 5,  8,  6, -9,  2,  1],
       [ 5,  9,  8,  3,  4,  2],
       [ 5,  9,  8,  6,  5,  4]])

In [40]:
#generate null matrix
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.zeros([4,5],dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.ones([3,4],dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
#array + range
n1 = np.arange(0,36)
print(n1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [46]:
#Reshaping of array
n1.reshape(3,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [47]:
n1.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [48]:
#array + range
n2 = np.arange(-36,36)
print(n2)

[-36 -35 -34 -33 -32 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19
 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1
   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35]


In [49]:
n2.reshape(9,8)

array([[-36, -35, -34, -33, -32, -31, -30, -29],
       [-28, -27, -26, -25, -24, -23, -22, -21],
       [-20, -19, -18, -17, -16, -15, -14, -13],
       [-12, -11, -10,  -9,  -8,  -7,  -6,  -5],
       [ -4,  -3,  -2,  -1,   0,   1,   2,   3],
       [  4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27],
       [ 28,  29,  30,  31,  32,  33,  34,  35]])

In [50]:
#Complex array
n3 = np.array([[5,8,9,2],[4,5,3,2]],dtype=complex)
n3

array([[5.+0.j, 8.+0.j, 9.+0.j, 2.+0.j],
       [4.+0.j, 5.+0.j, 3.+0.j, 2.+0.j]])

**Stacking**

In [51]:
a = np.array([[6,8,8,3,2],[8,9,4,3,1]])
b = np.array([[4,8,9,4,3]])

In [52]:
print(a)

[[6 8 8 3 2]
 [8 9 4 3 1]]


In [53]:
print(b)

[[4 8 9 4 3]]


In [54]:
#Vertical Stacking
np.vstack((a,b))

array([[6, 8, 8, 3, 2],
       [8, 9, 4, 3, 1],
       [4, 8, 9, 4, 3]])

In [55]:
#Horizontal Stacking
np.hstack((a,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [56]:
print(a)

[[6 8 8 3 2]
 [8 9 4 3 1]]


In [57]:
#Transpose of array
np.transpose(a)

array([[6, 8],
       [8, 9],
       [8, 4],
       [3, 3],
       [2, 1]])

In [58]:
a.T

array([[6, 8],
       [8, 9],
       [8, 4],
       [3, 3],
       [2, 1]])

In [59]:
import numpy as np

a = np.array([4, 6, 7, 2, 3])
print(a)

[4 6 7 2 3]


In [60]:
b = np.array([[1,2,"ABC",4,5],[3,4,5,6,7],[75,45,32,12,11]])
print(b)

[['1' '2' 'ABC' '4' '5']
 ['3' '4' '5' '6' '7']
 ['75' '45' '32' '12' '11']]


In [61]:
b = np.array([[1,2,"ABC",4,5],[3,4,5,6,7],[75,45,32,12,11]])

b1 = []
b2 = []
for val in b:
  for i in val:
    try:
      #print(int(i))
      b2.append(int(i))
    except:
      #print(ord(i[0]),ord(i[1]),ord(i[2]))
      b2.append(ord(i[0])+ord(i[1])+ord(i[2]))
    b1.append(b2)
    b2 = []

In [62]:
print(b1)

[[1], [2], [198], [4], [5], [3], [4], [5], [6], [7], [75], [45], [32], [12], [11]]


In [63]:
print(b2)

[]


In [64]:
print(np.array(b1).reshape(3,5))

[[  1   2 198   4   5]
 [  3   4   5   6   7]
 [ 75  45  32  12  11]]


# Numpy_2

In [65]:
import numpy as np
a = np.array([[3,5,8],[2,8,6],[1,2,3]])
print(a)

[[3 5 8]
 [2 8 6]
 [1 2 3]]


In [66]:
b = np.array([[3,2,1]])
print(b)

[[3 2 1]]


In [68]:
# Dot multiplication of matrix
np.dot(a,b.T)

array([[27],
       [28],
       [10]])

In [69]:
#3x + 2y + z = 45
#x + y + 5z = 67
#5x + 5y + 2z = 50

In [70]:
A = np.array([[3,2,1],[1,1,5],[5,5,2]])
print(A)

[[3 2 1]
 [1 1 5]
 [5 5 2]]


In [71]:
X = np.array([['x'],['y'],['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [72]:
B = np.array([[45],[67],[50]])
print(B)

[[45]
 [67]
 [50]]


In [73]:
#A.X = B
#X = inv(A).B

A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1.00000000e+00 -4.34782609e-02 -3.91304348e-01]
 [-1.00000000e+00 -4.34782609e-02  6.08695652e-01]
 [-1.20676416e-17  2.17391304e-01 -4.34782609e-02]]


In [74]:
X = np.dot(A_inv,B)
print(X)

[[ 22.52173913]
 [-17.47826087]
 [ 12.39130435]]


In [75]:
np.dot(A,X)

array([[45.],
       [67.],
       [50.]])